# ----------------------------------------------------------------------------------------------------
# Pipeline used by the azd command
# ----------------------------------------------------------------------------------------------------
name: dadabase-blazor-azd

infra:
  provider: bicep
  path: infra/Bicep
  module: main

pipeline:
  provider: github

services:
  web:
    project: ./src/web/Website/
    language: csharp
    host: appservice
