truncate table NationalParks
go


INSERT INTO NationalParks (type, name, state, latitude, longitude, description) VALUES
('National Park', 'Acadia National Park', 'Maine', 44.338974, -68.273430, 'The only national park in New England, featuring a wild coastal wilderness of mountains, sea cliffs, and beaches.'),
('National Park', 'American Samoa National Park', 'American Samoa', -14.235000, -170.688000, 'A tropical park protecting coral reefs, volcanic peaks, and Polynesian culture.'),
('National Park', 'Arches National Park', 'Utah', 38.733082, -109.592514, 'Home to the world''s largest concentration of natural sandstone arches set in dramatic desert scenery.'),
('National Park', 'Badlands National Park', 'South Dakota', 43.855438, -102.339691, 'A rugged landscape of sharply eroded buttes and colorful eroded hills spanning grassland prairie.'),
('National Park', 'Big Bend National Park', 'Texas', 29.127500, -103.242500, 'Vast Chihuahuan Desert wilderness alongside the Rio Grande with dramatic canyons and peaks.'),
('National Park', 'Biscayne National Park', 'Florida', 25.481000, -80.208600, 'A primarily underwater park safeguarding coral reefs, mangrove islands, and marine life.'),
('National Park', 'Black Canyon of the Gunnison National Park', 'Colorado', 38.575047, -107.724570, 'Features steep, dramatic canyon walls carved by the Gunnison River through ancient rock.'),
('National Park', 'Bryce Canyon National Park', 'Utah', 37.593048, -112.187332, 'Known for its thousands of vibrant hoodoos-tall, thin spires of rock-in a high desert setting.'),
('National Park', 'Canyonlands National Park', 'Utah', 38.326875, -109.878286, 'A vast wilderness of canyons, mesas, and buttes carved by the Colorado River.'),
('National Park', 'Capitol Reef National Park', 'Utah', 38.089600, -111.149910, 'Features colorful sandstone cliffs, domes, and the Waterpocket Fold-a 100 mile geological wrinkle.'),
('National Park', 'Carlsbad Caverns National Park', 'New Mexico', 32.147938, -104.556584, 'Famed for its vast limestone caves, including the spectacular Big Room with massive stalactites.'),
('National Park', 'Channel Islands National Park', 'California', 33.998028, -119.772949, 'A biodiversity hotspot and "Galapagos of North America,” with unique island ecosystems.'),
('National Park', 'Congaree National Park', 'South Carolina', 33.791300, -80.524700, 'Old growth bottomland hardwood forest with one of the tallest deciduous tree canopies in the U.S.'),
('National Park', 'Crater Lake National Park', 'Oregon', 42.944611, -122.109245, 'Protects North America''s deepest, clear blue lake formed in a volcanic caldera.'),
('National Park', 'Cuyahoga Valley National Park', 'Ohio', 41.280000, -81.567000, 'A lush, glacier-sculpted green oasis between Cleveland and Akron ideal for biking and waterfalls.'),
('National Park', 'Death Valley National Park', 'California, Nevada', 36.505389, -117.079407, 'Home to the lowest, hottest, driest point in North America with dunes, salt flats, and badlands.'),
('National Park', 'Denali National Park', 'Alaska', 63.129887, -151.197418, 'Encompasses North America''s tallest peak and vast subarctic wilderness.'),
('National Park', 'Dry Tortugas National Park', 'Florida', 24.628510, -82.873030, 'Remote reef-fringed islands featuring Fort Jefferson and vibrant coral reefs.'),
('National Park', 'Everglades National Park', 'Florida', 25.286615, -80.898651, 'A vast "river of grass” wetland sanctuary home to unique wildlife like alligators and manatees.'),
('National Park', 'Gates of the Arctic National Park', 'Alaska', 67.915199, -153.463730, 'An unfenced, roadless wilderness north of the Arctic Circle with tundra and mountains.'),
('National Park', 'Gateway Arch National Park', 'Missouri', 38.624700, -90.184800, 'Centered on the iconic Gateway Arch celebrating westward expansion over the Mississippi River.'),
('National Park', 'Glacier Bay National Park', 'Alaska', 58.665806, -136.900208, 'World class sights of calving glaciers, fjords, and lush temperate rainforests in southeast Alaska.'),
('National Park', 'Glacier National Park', 'Montana', 48.759613, -113.787023, 'Spectacular alpine landscapes with turquoise lakes, glaciers, and iconic Going to the Sun Road.'),
('National Park', 'Grand Canyon National Park', 'Arizona', 36.266033, -112.363808, 'A monumental gorge carved by the Colorado River showcasing colorful layered rocks.'),
('National Park', 'Grand Teton National Park', 'Wyoming', 43.790802, -110.684944, 'Jagged peaks rise above alpine lakes in a stunning valley known as Jackson Hole.'),
('National Park', 'Great Basin National Park', 'Nevada', 38.980000, -114.301000, 'A high-desert park featuring ancient bristlecone pines, mountains, and the Lehman Caves.'),
('National Park', 'Great Sand Dunes National Park', 'Colorado', 37.791667, -105.594400, 'Home to North America''s tallest sand dunes backed by mountains, prairie, and creekland.'),
('National Park', 'Great Smoky Mountains National Park', 'Tennessee, North Carolina', 35.611763, -83.489548, 'America''s most visited park, famed for its misty mountains, biodiversity, and Appalachian heritage.'),
('National Park', 'Guadalupe Mountains National Park', 'Texas', 31.901900, -104.844100, 'Protects rugged peaks, canyons, and the highest point in Texas in a remote desert setting.'),
('National Park', 'Haleakalā National Park', 'Hawaii', 20.701283, -156.173325, 'Preserves a massive volcanic crater and native ecosystems atop Maui.'),
('National Park', 'Hawaiʻi Volcanoes National Park', 'Hawaii', 19.419400, -155.288100, 'Features two of Earth''s most active volcanoes and dramatic volcanic landscapes.'),
('National Park', 'Hot Springs National Park', 'Arkansas', 34.521530, -93.042267, 'The oldest federally protected park, offering historic bathhouses and thermal springs in a small mountain setting.'),
('National Park', 'Indiana Dunes National Park', 'Indiana', 41.653600, -87.052000, 'Dynamic dunes, oak woodlands, and wetlands along Lake Michigan''s south shore.'),
('National Park', 'Isle Royale National Park', 'Michigan', 48.071100, -88.539000, 'A remote island in Lake Superior with wolves, moose, and pristine wilderness trails.'),
('National Park', 'Joshua Tree National Park', 'California', 33.881866, -115.900650, 'Where the Mojave and Colorado deserts meet, featuring iconic Joshua trees and rugged boulders.'),
('National Park', 'Katmai National Park', 'Alaska', 58.597813, -154.693756, 'Renowned for bear-viewing and the Valley of Ten Thousand Smokes volcanic landscape.'),
('National Park', 'Kenai Fjords National Park', 'Alaska', 60.043777, -149.816360, 'Coastal fjords filled with glaciers and marine life, including whales and sea otters.'),
('National Park', 'Kings Canyon National Park', 'California', 36.887000, -118.555000, 'Deep glacial valleys, massive sequoias, and high mountain peaks characterize this rugged terrain.'),
('National Park', 'Kobuk Valley National Park', 'Alaska', 67.514500, -159.277000, 'Home to great sand dunes, caribou migrations, and remote Arctic wilderness.'),
('National Park', 'Lake Clark National Park', 'Alaska', 60.412697, -154.323502, 'Volcanic peaks, turquoise lakes, and salmon streams in a remote Alaskan setting.'),
('National Park', 'Lassen Volcanic National Park', 'California', 40.497000, -121.420000, 'A volcanic wonderland of boiling mud pots, fumaroles, and four types of volcanoes.'),
('National Park', 'Mammoth Cave National Park', 'Kentucky', 37.183640, -86.159943, 'The world''s longest known cave system, with more than 400 miles of underground passages.'),
('National Park', 'Mesa Verde National Park', 'Colorado', 37.230873, -108.461838, 'Preserves ancient Pueblo cliff dwellings like Cliff Palace perched on sandstone cliffs.'),
('National Park', 'Mount Rainier National Park', 'Washington', 46.879967, -121.726906, 'Centered on majestic Mt. Rainier with glaciers, wildflower meadows, and old-growth forest.'),
('National Park', 'New River Gorge National Park', 'West Virginia', 38.064600, -81.072500, 'Deep river gorge with one of the longest steel arch bridges and premier whitewater.'),
('National Park', 'North Cascades National Park', 'Washington', 48.771900, -121.298900, 'A rugged wilderness filled with peaks, glaciers, and remote alpine lakes.'),
('National Park', 'Olympic National Park', 'Washington', 47.802100, -123.604400, 'Encompasses mountains, temperate rainforest, and wild Pacific coastline.'),
('National Park', 'Petrified Forest National Park', 'Arizona', 34.909988, -109.806793, 'Famous for colorful petrified wood, Painted Desert vistas, and archaeological ruins.'),
('National Park', 'Pinnacles National Park', 'California', 36.491508, -121.197243, 'Preserves ancient volcanic spires, talus caves, and is habitat for California condors.'),
('National Park', 'Redwood National Park', 'California', 41.213181, -124.004631, 'Walk among towering old growth redwoods and explore coastal rivers and prairies.'),
('National Park', 'Rocky Mountain National Park', 'Colorado', 40.343182, -105.688103, 'High alpine peaks, pristine lakes, and abundant wildlife characterize this mountain park.'),
('National Park', 'Saguaro National Park', 'Arizona', 32.296900, -111.166900, 'Dedicated to the iconic saguaro cactus forest of the Sonoran Desert around Tucson.'),
('National Park', 'Sequoia National Park', 'California', 36.486400, -118.565800, 'Home to massive sequoias including General Sherman-the largest tree on earth-and alpine high country.'),
('National Park', 'Shenandoah National Park', 'Virginia', 38.700516, -78.292694, 'Skyline Drive loops through forested Blue Ridge Mountains with waterfalls and abundant wildlife.'),
('National Park', 'Theodore Roosevelt National Park', 'North Dakota', 46.979000, -103.538000, 'Badlands terrain named to honor Teddy Roosevelt, with bison herds and prairie dog towns.'),
('National Park', 'Virgin Islands National Park', 'U.S. Virgin Islands', 18.343500, -64.798500, 'Tropical park preserving beaches, coral reefs, and historic plantation ruins.'),
('National Park', 'Voyageurs National Park', 'Minnesota', 48.450000, -92.850000, 'Water-based park of interconnected lakes, boreal forests, and historic trade routes.'),
('National Park', 'White Sands National Park', 'New Mexico', 32.779720, -106.171669, 'World''s largest gypsum dune field with otherworldly white sand dunes.'),
('National Park', 'Wind Cave National Park', 'South Dakota', 43.587800, -103.450300, 'Home to one of the world''s longest boxwork cave systems and mixed-grass prairie.'),
('National Park', 'Wrangell-St. Elias National Park', 'Alaska', 61.710445, 142.985687, 'The largest national park in the United States, spanning approximately 13.2 million acres of towering volcanic and glaciated mountain ranges-including Mount St. Elias-and vast wilderness from sea level to 18,008 ft peaks.'),
('National Park', 'Yellowstone National Park', 'Wyoming', 44.427895, 110.588379, 'The world''s first national park, famed for hydrothermal features like Old Faithful and abundant megafauna.'),
('National Park', 'Yosemite National Park', 'California', 37.865101, 119.538330, 'Iconic granite cliffs, giant sequoias, waterfalls, and deep valleys define this legendary park'),
('National Park', 'Zion National Park', 'Utah', 37.297817, 113.028770, 'Known for its towering red sandstone cliffs, narrow canyons, and the Virgin River''s carved landscapes')

Select * From NationalParks


