// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelTracker.Data;

#nullable disable

namespace TravelTracker.Data.Migrations
{
    [DbContext(typeof(TravelTrackerDbContext))]
    [Migration("20251025115713_AddTripNameToLocation")]
    partial class AddTripNameToLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelTracker.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LocationTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasDefaultValue("[]");

                    b.Property<string>("TripName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.HasIndex("StartDate");

                    b.HasIndex("State");

                    b.HasIndex("UserId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TravelTracker.Data.Models.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LocationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "RV Park or campground",
                            Name = "RV Park"
                        },
                        new
                        {
                            Id = 2,
                            Description = "US National Park",
                            Name = "National Park"
                        },
                        new
                        {
                            Id = 3,
                            Description = "US National Monument",
                            Name = "National Monument"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Harvest Host location",
                            Name = "Harvest Host"
                        },
                        new
                        {
                            Id = 5,
                            Description = "State Park",
                            Name = "State Park"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Family or friends location",
                            Name = "Family"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Other location type",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("TravelTracker.Data.Models.NationalPark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("State");

                    b.ToTable("NationalParks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The only national park in New England, featuring a wild coastal wilderness of mountains, sea cliffs, and beaches.",
                            Latitude = 44.338974,
                            Longitude = -68.273430000000005,
                            Name = "Acadia National Park",
                            State = "Maine",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A tropical park protecting coral reefs, volcanic peaks, and Polynesian culture.",
                            Latitude = -14.234999999999999,
                            Longitude = -170.68799999999999,
                            Name = "American Samoa National Park",
                            State = "American Samoa",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Home to the world's largest concentration of natural sandstone arches set in dramatic desert scenery.",
                            Latitude = 38.733082000000003,
                            Longitude = -109.59251399999999,
                            Name = "Arches National Park",
                            State = "Utah",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A rugged landscape of sharply eroded buttes and colorful eroded hills spanning grassland prairie.",
                            Latitude = 43.855437999999999,
                            Longitude = -102.339691,
                            Name = "Badlands National Park",
                            State = "South Dakota",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vast Chihuahuan Desert wilderness alongside the Rio Grande with dramatic canyons and peaks.",
                            Latitude = 29.127500000000001,
                            Longitude = -103.24250000000001,
                            Name = "Big Bend National Park",
                            State = "Texas",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A primarily underwater park safeguarding coral reefs, mangrove islands, and marine life.",
                            Latitude = 25.481000000000002,
                            Longitude = -80.208600000000004,
                            Name = "Biscayne National Park",
                            State = "Florida",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Features steep, dramatic canyon walls carved by the Gunnison River through ancient rock.",
                            Latitude = 38.575046999999998,
                            Longitude = -107.72457,
                            Name = "Black Canyon of the Gunnison National Park",
                            State = "Colorado",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Known for its thousands of vibrant hoodoos-tall, thin spires of rock-in a high desert setting.",
                            Latitude = 37.593048000000003,
                            Longitude = -112.187332,
                            Name = "Bryce Canyon National Park",
                            State = "Utah",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A vast wilderness of canyons, mesas, and buttes carved by the Colorado River.",
                            Latitude = 38.326875000000001,
                            Longitude = -109.878286,
                            Name = "Canyonlands National Park",
                            State = "Utah",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Features colorful sandstone cliffs, domes, and the Waterpocket Fold-a 100 mile geological wrinkle.",
                            Latitude = 38.089599999999997,
                            Longitude = -111.14991000000001,
                            Name = "Capitol Reef National Park",
                            State = "Utah",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Famed for its vast limestone caves, including the spectacular Big Room with massive stalactites.",
                            Latitude = 32.147938000000003,
                            Longitude = -104.556584,
                            Name = "Carlsbad Caverns National Park",
                            State = "New Mexico",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A biodiversity hotspot and Galapagos of North America, with unique island ecosystems.",
                            Latitude = 33.998027999999998,
                            Longitude = -119.772949,
                            Name = "Channel Islands National Park",
                            State = "California",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Old growth bottomland hardwood forest with one of the tallest deciduous tree canopies in the U.S.",
                            Latitude = 33.7913,
                            Longitude = -80.524699999999996,
                            Name = "Congaree National Park",
                            State = "South Carolina",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Protects North America's deepest, clear blue lake formed in a volcanic caldera.",
                            Latitude = 42.944611000000002,
                            Longitude = -122.109245,
                            Name = "Crater Lake National Park",
                            State = "Oregon",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 15,
                            Description = "A lush, glacier-sculpted green oasis between Cleveland and Akron ideal for biking and waterfalls.",
                            Latitude = 41.280000000000001,
                            Longitude = -81.566999999999993,
                            Name = "Cuyahoga Valley National Park",
                            State = "Ohio",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Home to the lowest, hottest, driest point in North America with dunes, salt flats, and badlands.",
                            Latitude = 36.505389000000001,
                            Longitude = -117.079407,
                            Name = "Death Valley National Park",
                            State = "California",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Encompasses North America's tallest peak and vast subarctic wilderness.",
                            Latitude = 63.129886999999997,
                            Longitude = -151.197418,
                            Name = "Denali National Park",
                            State = "Alaska",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Remote reef-fringed islands featuring Fort Jefferson and vibrant coral reefs.",
                            Latitude = 24.628509999999999,
                            Longitude = -82.87303,
                            Name = "Dry Tortugas National Park",
                            State = "Florida",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 19,
                            Description = "A vast river of grass wetland sanctuary home to unique wildlife like alligators and manatees.",
                            Latitude = 25.286615000000001,
                            Longitude = -80.898651000000001,
                            Name = "Everglades National Park",
                            State = "Florida",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 20,
                            Description = "An unfenced, roadless wilderness north of the Arctic Circle with tundra and mountains.",
                            Latitude = 67.915199000000001,
                            Longitude = -153.46373,
                            Name = "Gates of the Arctic National Park",
                            State = "Alaska",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Centered on the iconic Gateway Arch celebrating westward expansion over the Mississippi River.",
                            Latitude = 38.624699999999997,
                            Longitude = -90.184799999999996,
                            Name = "Gateway Arch National Park",
                            State = "Missouri",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 22,
                            Description = "World class sights of calving glaciers, fjords, and lush temperate rainforests in southeast Alaska.",
                            Latitude = 58.665806000000003,
                            Longitude = -136.90020799999999,
                            Name = "Glacier Bay National Park",
                            State = "Alaska",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Spectacular alpine landscapes with turquoise lakes, glaciers, and iconic Going to the Sun Road.",
                            Latitude = 48.759613000000002,
                            Longitude = -113.787023,
                            Name = "Glacier National Park",
                            State = "Montana",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 24,
                            Description = "A monumental gorge carved by the Colorado River showcasing colorful layered rocks.",
                            Latitude = 36.266033,
                            Longitude = -112.36380800000001,
                            Name = "Grand Canyon National Park",
                            State = "Arizona",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Jagged peaks rise above alpine lakes in a stunning valley known as Jackson Hole.",
                            Latitude = 43.790801999999999,
                            Longitude = -110.684944,
                            Name = "Grand Teton National Park",
                            State = "Wyoming",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 26,
                            Description = "A high-desert park featuring ancient bristlecone pines, mountains, and the Lehman Caves.",
                            Latitude = 38.979999999999997,
                            Longitude = -114.301,
                            Name = "Great Basin National Park",
                            State = "Nevada",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Home to North America's tallest sand dunes backed by mountains, prairie, and creekland.",
                            Latitude = 37.791666999999997,
                            Longitude = -105.59439999999999,
                            Name = "Great Sand Dunes National Park",
                            State = "Colorado",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 28,
                            Description = "America's most visited park, famed for its misty mountains, biodiversity, and Appalachian heritage.",
                            Latitude = 35.611763000000003,
                            Longitude = -83.489547999999999,
                            Name = "Great Smoky Mountains National Park",
                            State = "Tennessee",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Protects rugged peaks, canyons, and the highest point in Texas in a remote desert setting.",
                            Latitude = 31.901900000000001,
                            Longitude = -104.8441,
                            Name = "Guadalupe Mountains National Park",
                            State = "Texas",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Preserves a massive volcanic crater and native ecosystems atop Maui.",
                            Latitude = 20.701283,
                            Longitude = -156.17332500000001,
                            Name = "Haleakala National Park",
                            State = "Hawaii",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Features two of Earth's most active volcanoes and dramatic volcanic landscapes.",
                            Latitude = 19.4194,
                            Longitude = -155.28809999999999,
                            Name = "Hawaii Volcanoes National Park",
                            State = "Hawaii",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 32,
                            Description = "The oldest federally protected park, offering historic bathhouses and thermal springs in a small mountain setting.",
                            Latitude = 34.521529999999998,
                            Longitude = -93.042266999999995,
                            Name = "Hot Springs National Park",
                            State = "Arkansas",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Dynamic dunes, oak woodlands, and wetlands along Lake Michigan's south shore.",
                            Latitude = 41.653599999999997,
                            Longitude = -87.052000000000007,
                            Name = "Indiana Dunes National Park",
                            State = "Indiana",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 34,
                            Description = "A remote island in Lake Superior with wolves, moose, and pristine wilderness trails.",
                            Latitude = 48.071100000000001,
                            Longitude = -88.539000000000001,
                            Name = "Isle Royale National Park",
                            State = "Michigan",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Where the Mojave and Colorado deserts meet, featuring iconic Joshua trees and rugged boulders.",
                            Latitude = 33.881866000000002,
                            Longitude = -115.90065,
                            Name = "Joshua Tree National Park",
                            State = "California",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Renowned for bear-viewing and the Valley of Ten Thousand Smokes volcanic landscape.",
                            Latitude = 58.597813000000002,
                            Longitude = -154.69375600000001,
                            Name = "Katmai National Park",
                            State = "Alaska",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Coastal fjords filled with glaciers and marine life, including whales and sea otters.",
                            Latitude = 60.043776999999999,
                            Longitude = -149.81636,
                            Name = "Kenai Fjords National Park",
                            State = "Alaska",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Deep glacial valleys, massive sequoias, and high mountain peaks characterize this rugged terrain.",
                            Latitude = 36.887,
                            Longitude = -118.55500000000001,
                            Name = "Kings Canyon National Park",
                            State = "California",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Home to great sand dunes, caribou migrations, and remote Arctic wilderness.",
                            Latitude = 67.514499999999998,
                            Longitude = -159.27699999999999,
                            Name = "Kobuk Valley National Park",
                            State = "Alaska",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Volcanic peaks, turquoise lakes, and salmon streams in a remote Alaskan setting.",
                            Latitude = 60.412697000000001,
                            Longitude = -154.32350199999999,
                            Name = "Lake Clark National Park",
                            State = "Alaska",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 41,
                            Description = "A volcanic wonderland of boiling mud pots, fumaroles, and four types of volcanoes.",
                            Latitude = 40.497,
                            Longitude = -121.42,
                            Name = "Lassen Volcanic National Park",
                            State = "California",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 42,
                            Description = "The world's longest known cave system, with more than 400 miles of underground passages.",
                            Latitude = 37.183639999999997,
                            Longitude = -86.159942999999998,
                            Name = "Mammoth Cave National Park",
                            State = "Kentucky",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Preserves ancient Pueblo cliff dwellings like Cliff Palace perched on sandstone cliffs.",
                            Latitude = 37.230873000000003,
                            Longitude = -108.461838,
                            Name = "Mesa Verde National Park",
                            State = "Colorado",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Centered on majestic Mt. Rainier with glaciers, wildflower meadows, and old-growth forest.",
                            Latitude = 46.879967000000001,
                            Longitude = -121.726906,
                            Name = "Mount Rainier National Park",
                            State = "Washington",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Deep river gorge with one of the longest steel arch bridges and premier whitewater.",
                            Latitude = 38.064599999999999,
                            Longitude = -81.072500000000005,
                            Name = "New River Gorge National Park",
                            State = "West Virginia",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 46,
                            Description = "A rugged wilderness filled with peaks, glaciers, and remote alpine lakes.",
                            Latitude = 48.771900000000002,
                            Longitude = -121.2989,
                            Name = "North Cascades National Park",
                            State = "Washington",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Encompasses mountains, temperate rainforest, and wild Pacific coastline.",
                            Latitude = 47.802100000000003,
                            Longitude = -123.6044,
                            Name = "Olympic National Park",
                            State = "Washington",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Famous for colorful petrified wood, Painted Desert vistas, and archaeological ruins.",
                            Latitude = 34.909987999999998,
                            Longitude = -109.806793,
                            Name = "Petrified Forest National Park",
                            State = "Arizona",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Preserves ancient volcanic spires, talus caves, and is habitat for California condors.",
                            Latitude = 36.491508000000003,
                            Longitude = -121.197243,
                            Name = "Pinnacles National Park",
                            State = "California",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Walk among towering old growth redwoods and explore coastal rivers and prairies.",
                            Latitude = 41.213180999999999,
                            Longitude = -124.004631,
                            Name = "Redwood National Park",
                            State = "California",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 51,
                            Description = "High alpine peaks, pristine lakes, and abundant wildlife characterize this mountain park.",
                            Latitude = 40.343181999999999,
                            Longitude = -105.688103,
                            Name = "Rocky Mountain National Park",
                            State = "Colorado",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Dedicated to the iconic saguaro cactus forest of the Sonoran Desert around Tucson.",
                            Latitude = 32.296900000000001,
                            Longitude = -111.1669,
                            Name = "Saguaro National Park",
                            State = "Arizona",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Home to massive sequoias including General Sherman-the largest tree on earth-and alpine high country.",
                            Latitude = 36.486400000000003,
                            Longitude = -118.5658,
                            Name = "Sequoia National Park",
                            State = "California",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Skyline Drive loops through forested Blue Ridge Mountains with waterfalls and abundant wildlife.",
                            Latitude = 38.700516,
                            Longitude = -78.292693999999997,
                            Name = "Shenandoah National Park",
                            State = "Virginia",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Badlands terrain named to honor Teddy Roosevelt, with bison herds and prairie dog towns.",
                            Latitude = 46.978999999999999,
                            Longitude = -103.538,
                            Name = "Theodore Roosevelt National Park",
                            State = "North Dakota",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Tropical park preserving beaches, coral reefs, and historic plantation ruins.",
                            Latitude = 18.343499999999999,
                            Longitude = -64.798500000000004,
                            Name = "Virgin Islands National Park",
                            State = "U.S. Virgin Islands",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Water-based park of interconnected lakes, boreal forests, and historic trade routes.",
                            Latitude = 48.450000000000003,
                            Longitude = -92.849999999999994,
                            Name = "Voyageurs National Park",
                            State = "Minnesota",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 58,
                            Description = "World's largest gypsum dune field with otherworldly white sand dunes.",
                            Latitude = 32.779719999999998,
                            Longitude = -106.17166899999999,
                            Name = "White Sands National Park",
                            State = "New Mexico",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Home to one of the world's longest boxwork cave systems and mixed-grass prairie.",
                            Latitude = 43.587800000000001,
                            Longitude = -103.4503,
                            Name = "Wind Cave National Park",
                            State = "South Dakota",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 60,
                            Description = "The largest national park in the United States, spanning approximately 13.2 million acres of towering volcanic and glaciated mountain ranges-including Mount St. Elias-and vast wilderness from sea level to 18,008 ft peaks.",
                            Latitude = 61.710445,
                            Longitude = 142.98568700000001,
                            Name = "Wrangell-St. Elias National Park",
                            State = "Alaska",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 61,
                            Description = "The world's first national park, famed for hydrothermal features like Old Faithful and abundant megafauna.",
                            Latitude = 44.427894999999999,
                            Longitude = 110.588379,
                            Name = "Yellowstone National Park",
                            State = "Wyoming",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Iconic granite cliffs, giant sequoias, waterfalls, and deep valleys define this legendary park",
                            Latitude = 37.865101000000003,
                            Longitude = 119.53833,
                            Name = "Yosemite National Park",
                            State = "California",
                            Type = "National Park"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Known fo6 its towering red sandstone cliffs, narrow canyons, and the Virgin River's carved landscapes",
                            Latitude = 37.297817000000002,
                            Longitude = 113.02876999999999,
                            Name = "Zion National Park",
                            State = "Utah",
                            Type = "National Park"
                        });
                });

            modelBuilder.Entity("TravelTracker.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntraIdUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("EntraIdUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TravelTracker.Data.Models.Location", b =>
                {
                    b.HasOne("TravelTracker.Data.Models.LocationType", "LocationTypeNavigation")
                        .WithMany()
                        .HasForeignKey("LocationTypeId");

                    b.Navigation("LocationTypeNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
