# API  Tests

# Variables
@baseServer = https://localhost:7134
@apiKey = myapikey

### Health check (no API key required)
GET {{baseServer}}/api/healthz

### Swagger file
GET {{baseServer}}/api/swagger/swagger.json

### Get National Parks
GET {{baseServer}}/api/nationalparks
Accept: application/json
X-API-Key: {{apiKey}}

###  Get locations
GET {{baseServer}}/api/locations
Accept: application/json
X-API-Key: {{apiKey}}

###  Get locations visited in Texas
GET {{baseServer}}/api/locations/by-state/TX
Accept: application/json
X-API-Key: {{apiKey}}

###  Get count of locations visited in each state
GET {{baseServer}}/api/locations/count-by-state
Accept: application/json
X-API-Key: {{apiKey}}

### Negative test - Missing API key should return 401
GET {{baseServer}}/api/nationalparks
Accept: application/json
