# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to scan and build WebApp on Pull Request - no app or bicep deploy
# ------------------------------------------------------------------------------------------------------------------------
# FYI: You need to set up some secrets before running this workflows - see CreateGitHubSecrets.md for details.
# ------------------------------------------------------------------------------------------------------------------------
name: 6.pr.scan.build
run-name: '6. PR Scan & Build'

on: 
  pull_request:
  workflow_dispatch:

# ------------------------------------------------------------------------------------------------------------------------
permissions:
  id-token: write
  contents: write
  actions: read
  pages: write
  security-events: write
  checks: write
  issues: write
  pull-requests: write
  packages: read

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  load-config:
    name: Load Project Config
    uses: ./.github/workflows/template-load-config.yml
    secrets: inherit

  scan-code:
    name: Scan Source Code
    uses: ./.github/workflows/template-scan-code.yml
    secrets: inherit
    with:
      runMSDevSecOpsScan: true
      runGHASScan: false
      runSBOM: false

# ------------------------------------------------------------------------------------------------------------------------
  build-app:
    name: Build WebApp
    uses: ./.github/workflows/template-webapp-build.yml
    needs: [load-config, scan-code]
    secrets: inherit
    with:
      envCode: 'dev'
      rootDirectory: '${{ needs.load-config.outputs.web_rootDirectory }}'
      projectName: '${{ needs.load-config.outputs.web_projectName }}'
      testDirectory: '${{ needs.load-config.outputs.web_testDirectory }}'
      testProjectName: '${{ needs.load-config.outputs.web_testProjectName }}'
      testApplication: true
      listFilesAfterBuild: true
